name: PR Workflow

on: pull_request

jobs:
  release:
    name: Release snapshot
    strategy:
      matrix:
        runner-platform:
          - ubuntu-latest
          - self-hosted
        include:
          - runner-platform: ubuntu-latest
            build-arch: linux/amd64
          - runner-platform: self-hosted
            build-arch: linux/arm64
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-prs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-prs-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: codetheweb/muse:${{ github.event.pull_request.head.sha }},codetheweb/muse:pr-${{ github.event.number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          platforms: ${{ matrix.build-arch }}

      - name: Create comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "pr-release"
          message: |
            #### :package: A new release has been made for this pull request.

            To play around with this PR, pull `codetheweb/muse:pr-${{ github.event.number }}` or `codetheweb/muse:${{ github.event.pull_request.head.sha }}`.

            Images are available for x64 and ARM64.

            > Latest commit: ${{ github.event.pull_request.head.sha }}
